### PR TITLE
Cards fixes #8

### LINKED ISSUE #8: Card-Component
create a card component that will display the pets which are up for adoption

### PR DESCRIPTION
**Pull request by qwel-exe**
fixes #8

### CODE REVIEW

**Comment by majjikishore007** [comment]
please provide the screenshot of what you have updated

**Comment by qwel-exe** [comment]
@majjikishore007 could you remove the labe as this is a proper pr

**Comment by qwel-exe** [comment]
> @majjikishore007 could you remove the labe as this is a proper pr

pls pls bro i did all my 4 prs to hacktoberfest and if this is makred as spam i cant get my tree :(

**Comment by qwel-exe** [comment]
@AnandDhakane01 bro pls

**Pull request closed without merging**
