### PR TITLE
Responsive Home Page #56

### PR DESCRIPTION
**Pull request by TheRealDarkCoder**
Changes:

(1) Changed the git links in Readme.md, they had links for arc-back-end.
(2) Made the frontend testimonial mobile friendly and responsive using tailwind classes.

### CODE REVIEW

**Comment by TheRealDarkCoder** [comment]
Issue #56

**Comment by majjikishore007** [comment]
> Changes:
> 
> (1) Changed the git links in Readme.md, they had links for arc-back-end. (2) Made the frontend testimonial mobile friendly and responsive using tailwind classes.

hey make sure to send pr to the staging branch

**Comment by TheRealDarkCoder** [comment]
Oh my bad, should I redo the PR?

**Comment by TheRealDarkCoder** [comment]
@majjikishore007 Changed base to staging

**Review by majjikishore007 — APPROVED** [review]
awsome work and thanks for contributing

**Pull request merged**
